### ISSUE TITLE
Access denied in Visual Studio

### ISSUE THREAD

**Issue by ellern** [Azure/servicefabric-samples#6]
I'm getting this error when trying to start a debug session in Visual Studio:

>Unable to copy file "C:\Samples\servicefabric-samples-master\servicefabric-samples-master\samples\Actors\VS2015\HelloWorld\packages\Microsoft.ServiceFabric.Actors.1.0.314-preview1\build\FabActUtil.exe" to "C:\Samples\servicefabric-samples-master\servicefabric-samples-master\samples\Actors\VS2015\HelloWorld\HelloWorld\bin\Debug\FabActUtil.exe". Access to the path 'C:\Samples\servicefabric-samples-master\servicefabric-samples-master\samples\Actors\VS2015\HelloWorld\HelloWorld\bin\Debug\FabActUtil.exe' is denied.	HelloWorld

I've also tried to start a new service fabric project, same result.

**Comment by varghesep** [comment]
You may try building the project first and see whether it shows some build errors. Other things you can try is to check on the platform is x64 in the VS. Also try closing the VS and a reboot of the system.

**Comment by ellern** [comment]
All projects build fine except the Application project, which throws the above error.

I've tried restarting, rebooting and even reinstalling the service fabric sdk, still no luck. I'm running VS2015RC side by side with VS2013.

**Comment by erichfrazer** [comment]
I'm seeing this issue too, and I work at Microsoft. I will post if I figure this out.
I too, am running VS 2013 and VS 2015.

**Comment by utillity** [comment]
having same issue - anyone have a solution yet? thanks!

**Comment by mthalman-msft** [comment]
Not sure how your system would get into this state but this error could occur if you already have a FabActUtil.exe file existing at the destination location and it is set to be read-only.  Have you tried deleting your bin folder?

**Comment by LyndseyPaxton** [comment]
Also having the same issue. VS2015 Update 2
Have rebooted and deleted contents of bin\debug folder

**Comment by okikie** [comment]
I was having this issue as well once I installed VS 2015 Update 1 side by side with my VS2010.  I ran into this error while trying to build my VS2010 project.

The one thing that worked for me was changing the Startup Project to something else.  My solution now rebuilds every time with no issue.

The con, it will still fail if you change your startup project back to the application project.  So if you need to debug, you would have to build, run the application outside VS, then Debug | Attach to Process... and select the running application.

**Comment by utillity** [comment]
@okikie you can right-click the project and choose "start debug" if it's not your startup project.

I solved it by changing the exe name of my startup project.

I hope MS will fix this at some point...

**Comment by okikie** [comment]
@utillity oh thank you!  for some reason, I always assumed it would try to rebuild before starting the app.. so I automatically thought this wouldn't work.

**Comment by hariramanathan** [comment]
I had the same issue. I fallowed all the steps in this link -> [https://azure.microsoft.com/en-us/documentation/articles/service-fabric-get-started/] but missed to perform the last step i.e., "Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Force -Scope CurrentUser" and still it did not work. So did a restart of my workstation and it started to work good :)

**Comment by WonderPanda** [comment]
I was able to resolve this issue by modifying the targets file. See this issue: https://github.com/Azure/service-fabric-issues/issues/26

**Comment by masnider** [comment]
In that case can we close this iteration of the issue or would you prefer to leave it open till the full fix is released?

**Comment by cestes001** [comment]
I've gone all the way down the list of fixes above and still no luck.  I have given every account on my machine full privileges to the folder in question and still get the same error 

{"Access to the path 'E:\\Lightroom\\_Reduced\\For Web\\test' is denied."}

The InnerException is null.  I just don't get it.

**Comment by MikkelHegn** [comment]
Are you on SDK version 2.3? Are you using Stateful services? What's the out put of the Handle Tool: https://technet.microsoft.com/en-us/sysinternals/handle?
